/** 操作员信息 **/
CREATE TABLE `os_user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` varchar(36) NOT NULL COMMENT '用户编码',
  `account` varchar(64) NOT NULL DEFAULT '' COMMENT '登录账户',
  `telephone` varchar(20) NOT NULL COMMENT '手机号码',
  `email` varchar(128) NOT NULL COMMENT '电子邮箱',
  `password` varchar(128) NOT NULL DEFAULT '',
  `salt` varchar(128) NOT NULL DEFAULT '',
  `name` varchar(64) NOT NULL DEFAULT '' COMMENT '真实姓名',
  `py` varchar(64) DEFAULT NULL,
  `header` varchar(256) NOT NULL DEFAULT '',
  `sex` varchar(4) DEFAULT NULL,
  `birth` date DEFAULT NULL,
  `mobile` varchar(20) NOT NULL DEFAULT '',
  `org_id` varchar(11) DEFAULT NULL,
  `dept_id` int(11) DEFAULT NULL,
  `province` varchar(20) DEFAULT NULL,
  `province_name` varchar(64) DEFAULT NULL,
  `city` varchar(20) DEFAULT NULL,
  `city_name` varchar(64) DEFAULT NULL,
  `area` varchar(20) DEFAULT NULL,
  `area_name` varchar(64) DEFAULT NULL,
  `street` varchar(20) DEFAULT NULL,
  `street_name` varchar(64) DEFAULT NULL,
  `address` varchar(256) DEFAULT NULL,
  `org_code` varchar(64) DEFAULT NULL,
  `memo` varchar(256) DEFAULT NULL COMMENT '备注',
  `create_id` varchar(64) DEFAULT NULL,
  `create_name` varchar(64) DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_id` varchar(64) DEFAULT NULL,
  `update_name` varchar(64) DEFAULT NULL,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` smallint(11) NOT NULL DEFAULT '1' COMMENT '用户状态：0-创建，1-已启用 ，2-锁定，3-停用',
  `deleted` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否删除：-1 删除，1 正常',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4;
alter table `os_user` add index idx_userid(`user_id`);
alter table `os_user` add index idx_account(`account`);